services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - "8090:80"
    volumes:
      - uploads:/var/www/html/uploads
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CHARSET: ${DB_CHARSET}
      DB_COLLATION: ${DB_COLLATION}

      CACHE_STORE: ${CACHE_STORE}
      REDIS_CLIENT: ${REDIS_CLIENT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB}

      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_CONNECTION: ${SESSION_CONNECTION}
      SESSION_LIFETIME: ${SESSION_LIFETIME}

      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}

      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      BROADCAST_CONNECTION: ${BROADCAST_CONNECTION}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}

    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - app-network


  mariadb:
    build:
      context: ./sql

    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mariadb-data:/var/lib/mysql

    networks:
      - app-network


  redis:
    build:
      context: ./redis

    volumes:
      - redis-data:/data

    networks:
      - app-network


volumes:
  mariadb-data:
  redis-data:
  uploads:

networks:
  app-network:
